name: Publish

on:
  release:  
    types: [prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Install packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Start environment services
        run: |
          cd samples
          bash start.sh -xe

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Stop environment services
        run: |
          cd samples
          bash stop.sh -xe
        
      - name: Create package(s)
        run: dotnet pack --version-suffix ${{format('tags-{0}', github.ref_name)}} --configuration Release --no-build
        
      - name: Publish packages
        run: dotnet nuget push **/*.nupkg -k ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
